### ISSUE TITLE
Chunks don't automatically load on startup

### ISSUE THREAD

**Issue by gragas** [gragas/adept#35]
I'm not sure why this is happening. If you are far from the original "spawn point" then the chunks immediately surrounding you will not be loaded immediately. Loading works correctly once the character moves far enough away from his marker, as expected.

I think this is because somewhere, someone hardcoded the camera to initially load the chunks around the original "spawn point" rather than where the character is on load. This should be an easy fix.

**Comment by benjamincongdon** [comment]
Yup. In GameTestScene, line 34 `MapManager.loadChunks(0,0)` is probably the culprit.

**Comment by benjamincongdon** [comment]
Fixed in #39.
